# Generated by Django 4.1.7 on 2023-03-09 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questions_body',
            new_name='body',
        ),
    ]
