# Generated by Django 4.1.7 on 2023-03-10 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_rename_questions_body_question_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200)),
                ('choices_A', models.CharField(max_length=100)),
                ('choices_B', models.CharField(max_length=100)),
                ('choices_C', models.CharField(max_length=100)),
                ('choices_D', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
