# Generated by Django 4.1.7 on 2023-03-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_singlechoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singlechoice',
            old_name='choices_A',
            new_name='choices_1',
        ),
        migrations.RenameField(
            model_name='singlechoice',
            old_name='choices_B',
            new_name='choices_2',
        ),
        migrations.RenameField(
            model_name='singlechoice',
            old_name='choices_C',
            new_name='choices_3',
        ),
        migrations.RenameField(
            model_name='singlechoice',
            old_name='choices_D',
            new_name='choices_4',
        ),
        migrations.AddField(
            model_name='singlechoice',
            name='right_answer',
            field=models.IntegerField(default=0),
        ),
    ]
