# Generated by Django 4.1.7 on 2023-03-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_rename_choices_a_singlechoice_choices_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlechoice',
            name='body',
        ),
        migrations.AlterField(
            model_name='singlechoice',
            name='choices_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='singlechoice',
            name='choices_2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='singlechoice',
            name='choices_3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='singlechoice',
            name='choices_4',
            field=models.CharField(max_length=200),
        ),
    ]
