# Generated by Django 4.1.7 on 2023-03-10 03:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_remove_singlechoice_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlechoice',
            name='body',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
