# Generated by Django 4.1.7 on 2023-03-19 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0006_singlechoice_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('choices_A', models.CharField(max_length=200)),
                ('choices_B', models.CharField(max_length=200)),
                ('choices_C', models.CharField(max_length=200)),
                ('choices_D', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('subject', models.IntegerField(choices=[(0, '语文'), (1, '英语'), (2, '数学')], null=True)),
                ('type', models.IntegerField(choices=[(0, '单项选择'), (1, '多项选择')])),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SubjectiveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('correct_answer', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('subject', models.IntegerField(choices=[(0, '语文'), (1, '英语'), (2, '数学')], null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='singlechoice',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='singlechoice',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='singlechoice',
            name='right_answer',
            field=models.CharField(max_length=1),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
