# Generated by Django 4.1.7 on 2023-03-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_choicequestion_subjectivequestion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectivequestion',
            options={'ordering': ['-id']},
        ),
    ]
