# Generated by Django 4.1.7 on 2023-03-19 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_subjectivequestion_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleChoice',
        ),
    ]
