# Generated by Django 4.1.7 on 2023-03-19 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_delete_singlechoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectivequestion',
            name='correct_answer',
        ),
    ]
