# Generated by Django 4.1.7 on 2023-03-19 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_remove_subjectivequestion_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectivequestion',
            name='image',
        ),
        migrations.AddField(
            model_name='subjectivequestion',
            name='correct_answer',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
