# Generated by Django 4.1.7 on 2023-03-19 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_remove_subjectivequestion_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectivequestion',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subjectivequestion',
            name='subject',
        ),
    ]
