# Generated by Django 4.1.7 on 2023-03-20 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0017_subjectivequestion_correct_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('blanks_num', models.IntegerField(default=1)),
                ('correct_answer_1', models.CharField(max_length=20)),
                ('correct_answer_2', models.CharField(max_length=20, null=True)),
                ('correct_answer_3', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('subject', models.IntegerField(choices=[(0, '语文'), (1, '英语'), (2, '数学')], null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjective', to=settings.AUTH_USER_MODEL),
        ),
    ]
