# Generated by Django 4.1.7 on 2023-03-20 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0018_blankquestion_alter_choicequestion_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blankquestion',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blank', to=settings.AUTH_USER_MODEL),
        ),
    ]
