# Generated by Django 4.1.7 on 2023-04-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_blankquestion_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blankquestion',
            name='subject',
            field=models.IntegerField(choices=[(0, '语文'), (1, '英语'), (2, '数学'), (3, '政治')], null=True),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='subject',
            field=models.IntegerField(choices=[(0, '语文'), (1, '英语'), (2, '数学'), (3, '政治')], null=True),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='subject',
            field=models.IntegerField(choices=[(0, '语文'), (1, '英语'), (2, '数学'), (3, '政治')], null=True),
        ),
    ]
