# Generated by Django 4.1.7 on 2023-04-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='major',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='classexam',
            old_name='class_id',
            new_name='classes',
        ),
        migrations.RemoveField(
            model_name='class',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='class',
            name='order_num',
        ),
    ]
