# Generated by Django 4.1.7 on 2023-04-10 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_exam_subject'),
        ('mark', '0004_answer_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='exam',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='exams.exam'),
            preserve_default=False,
        ),
    ]
