# Generated by Django 4.1.7 on 2023-04-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0005_answer_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scores',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
