# Generated by Django 4.1.7 on 2023-04-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_create_time_exam_desc_exam_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='questions_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='examquestion',
            table='exams_exam_question',
        ),
    ]
