# Generated by Django 4.1.7 on 2023-04-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_rename_questions_id_examquestion_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.IntegerField(choices=[(0, '语文'), (1, '英语'), (2, '数学'), (3, '政治')]),
        ),
    ]
