# Generated by Django 4.1.7 on 2023-04-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exams', '0006_alter_exam_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
